import { Component } from '@angular/core';

@Component({
  selector: 'app-content-removal-policy',
  templateUrl: './content-removal-policy.component.html',
  styleUrls: ['./content-removal-policy.component.scss'],
})
export class ContentRemovalPolicyComponent {
  violationItems = [
    'CONTENT_REMOVAL_POLICY.VIOLATIONS.INSULT',
    'CONTENT_REMOVAL_POLICY.VIOLATIONS.HATE_SPEECH',
    'CONTENT_REMOVAL_POLICY.VIOLATIONS.COPYRIGHT',
    'CONTENT_REMOVAL_POLICY.VIOLATIONS.PERSONAL_DATA',
    'CONTENT_REMOVAL_POLICY.VIOLATIONS.ILLEGAL',
  ];

  requiredInfoItems = [
    'CONTENT_REMOVAL_POLICY.REQUIRED_INFO.NAME',
    'CONTENT_REMOVAL_POLICY.REQUIRED_INFO.EMAIL',
    'CONTENT_REMOVAL_POLICY.REQUIRED_INFO.CONTENT_LINK',
    'CONTENT_REMOVAL_POLICY.REQUIRED_INFO.DESCRIPTION',
  ];

  reviewItems = [
    'CONTENT_REMOVAL_POLICY.REVIEW_PROCESS.REMOVE',
    'CONTENT_REMOVAL_POLICY.REVIEW_PROCESS.EDIT',
    'CONTENT_REMOVAL_POLICY.REVIEW_PROCESS.KEEP',
  ];

  removalRightsItems = [
    'CONTENT_REMOVAL_POLICY.REMOVAL_RIGHTS.RULE_VIOLATION',
    'CONTENT_REMOVAL_POLICY.REMOVAL_RIGHTS.LEGAL_VIOLATION',
    'CONTENT_REMOVAL_POLICY.REMOVAL_RIGHTS.USER_SAFETY',
  ];
}