import { Component } from '@angular/core';

@Component({
  selector: 'app-privacy-policy',
  templateUrl: './privacy-policy.component.html',
  styleUrls: ['./privacy-policy.component.scss'],
})
export class PrivacyPolicyComponent {
  introItems = [
    'PRIVACY_POLICY.INTRO.P1',
    'PRIVACY_POLICY.INTRO.P2',
    'PRIVACY_POLICY.INTRO.P3',
    'PRIVACY_POLICY.INTRO.P4',
    'PRIVACY_POLICY.INTRO.P5',
  ];

  collectedDataItems = [
    'PRIVACY_POLICY.COLLECTED_DATA.EMAIL',
    'PRIVACY_POLICY.COLLECTED_DATA.PHOTOS',
    'PRIVACY_POLICY.COLLECTED_DATA.MEMORIAL_TEXTS',
    'PRIVACY_POLICY.COLLECTED_DATA.COMMENTS',
    'PRIVACY_POLICY.COLLECTED_DATA.IP_ADDRESS',
    'PRIVACY_POLICY.COLLECTED_DATA.DEVICE_INFO',
  ];

  usagePurposeItems = [
    'PRIVACY_POLICY.USAGE_PURPOSES.PROVIDE_SERVICE',
    'PRIVACY_POLICY.USAGE_PURPOSES.SECURITY',
    'PRIVACY_POLICY.USAGE_PURPOSES.ACCOUNTS',
    'PRIVACY_POLICY.USAGE_PURPOSES.PERFORMANCE',
  ];

  dataSharingItems = [
    'PRIVACY_POLICY.DATA_SHARING.PAYMENT_PROVIDERS',
    'PRIVACY_POLICY.DATA_SHARING.HOSTING_PROVIDERS',
    'PRIVACY_POLICY.DATA_SHARING.AUTHORITIES',
  ];

  userRightsItems = [
    'PRIVACY_POLICY.USER_RIGHTS.ACCESS',
    'PRIVACY_POLICY.USER_RIGHTS.CORRECTION',
    'PRIVACY_POLICY.USER_RIGHTS.DELETION',
  ];
}