import { Component } from '@angular/core';

@Component({
  selector: 'app-moderation-policy',
  templateUrl: './moderation-policy.component.html',
  styleUrls: ['./moderation-policy.component.scss'],
})
export class ModerationPolicyComponent {
  purposeItems = [
    'MODERATION_POLICY.PURPOSES.RESPECTFUL_COMMUNITY',
    'MODERATION_POLICY.PURPOSES.PREVENT_HARMFUL_CONTENT',
    'MODERATION_POLICY.PURPOSES.USER_SAFETY',
  ];

  scopeItems = [
    'MODERATION_POLICY.SCOPE.MEMORIAL_PAGES',
    'MODERATION_POLICY.SCOPE.PHOTOS',
    'MODERATION_POLICY.SCOPE.USER_COMMENTS',
    'MODERATION_POLICY.SCOPE.PROFILE_INFO',
  ];

  decisionItems = [
    'MODERATION_POLICY.DECISIONS.REMOVE_COMMENT',
    'MODERATION_POLICY.DECISIONS.REMOVE_CONTENT',
    'MODERATION_POLICY.DECISIONS.EDIT_CONTENT',
    'MODERATION_POLICY.DECISIONS.RESTRICT_ACCESS',
  ];

  criteriaItems = [
    'MODERATION_POLICY.CRITERIA.INSULTING_COMMENTS',
    'MODERATION_POLICY.CRITERIA.HATE_SPEECH',
    'MODERATION_POLICY.CRITERIA.SPAM',
    'MODERATION_POLICY.CRITERIA.ADVERTISING',
    'MODERATION_POLICY.CRITERIA.INAPPROPRIATE_CONTENT',
  ];
}